// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcyvQn7S5wibKl0cn9pUZImRX27bc8Vz0',
    appId: '1:624111056535:web:cab959326c14f1a30bdbd2',
    messagingSenderId: '624111056535',
    projectId: 'my-first-project-ec805',
    authDomain: 'my-first-project-ec805.firebaseapp.com',
    databaseURL: 'https://my-first-project-ec805-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-ec805.firebasestorage.app',
    measurementId: 'G-YK27S2ZWBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLkYrkUG1LvuxP17CMyXv1Vci5BqdAgw',
    appId: '1:624111056535:android:5a36e8b1e71ebd8b0bdbd2',
    messagingSenderId: '624111056535',
    projectId: 'my-first-project-ec805',
    databaseURL: 'https://my-first-project-ec805-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-ec805.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbahpH4en9NlkBAdgbusNvkc_z8Nz1z7o',
    appId: '1:624111056535:ios:038e60051034affa0bdbd2',
    messagingSenderId: '624111056535',
    projectId: 'my-first-project-ec805',
    databaseURL: 'https://my-first-project-ec805-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-ec805.firebasestorage.app',
    iosBundleId: 'com.kisan.app.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbahpH4en9NlkBAdgbusNvkc_z8Nz1z7o',
    appId: '1:624111056535:ios:48242bed0b1869e60bdbd2',
    messagingSenderId: '624111056535',
    projectId: 'my-first-project-ec805',
    databaseURL: 'https://my-first-project-ec805-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-ec805.firebasestorage.app',
    iosBundleId: 'com.example.kisanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcyvQn7S5wibKl0cn9pUZImRX27bc8Vz0',
    appId: '1:624111056535:web:339934389b56004b0bdbd2',
    messagingSenderId: '624111056535',
    projectId: 'my-first-project-ec805',
    authDomain: 'my-first-project-ec805.firebaseapp.com',
    databaseURL: 'https://my-first-project-ec805-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-project-ec805.firebasestorage.app',
    measurementId: 'G-H7VV6K97WW',
  );

}